full_name = input("Name: ")
age = input("Age: ")
college_name = input("College: ")
branch = input("Branch: ")
city = input("City: ")

print("----------------------")
print("      STUDENT ID CARD")
print("----------------------")
print("Name   :", full_name)
print("Age    :", age)
print("College:", college_name)
print("Branch :", branch)
print("City   :", city)
print("----------------------")